backend:
  name: git-gateway
  branch: main
  repo: vosaul/AUDREY
publish_mode: editorial_workflow
media_folder: /images
public_folder: /images

collections:

- name: pages-en
  label: Pages English
  editor:
    preview: true
  files:
  - label: Homepage
    name: homepage
    file: "/content/en/data/home.yml"
    fields:
    - name: title
      widget: string
    - name: subtitle
      widget: string
    - name: text
      widget: string
    - name: about_section
      label: About section
      widget: object
      fields: 
      - {name: intro, widget: text}
      - {name: decor_center, widget: image}
      - {name: decor_left, widget: image}
      - {name: decor_right, widget: image}
      - {name: image_1, widget: image}
      - {name: image_2, widget: image}
      - name: about_box
        widget: object
        fields: 
        - {name: image, widget: image}
        - {name: name, widget: string}
        - {name: title, widget: string}
        - {name: text, widget: markdown}

      - name: therapies
        widget: object
        allow_add: false
        fields: 
        - {name: cta_label, widget: string}
        - {name: cta_link, widget: string}        
        - {name: title, widget: string}
        - name: items
          allow_add: false
          widget: list
          fields: 
          - {name: title, widget: string}
          - {name: image, widget: image}

    - name: gallery
      widget: list
  #    field:
  #    - {name: slide, widget: list, field: {name: image, widget: image}}
  #      
    - name: decor_gallery
      widget: image
    - name: distance
      widget: object
      fields: 
      - {name: decor_center, widget: image}
      - {name: title, widget: string}
      - {name: text, widget: markdown}
      - name: three_t
        allow_add: false
        widget: list
        fields: 
        - {name: label, widget: string}
        - {name: image, widget: image}
    - name: contact
      widget: object
      fields:
      - {name: image, widget: image}
      - {name: text, widget: list}
 
  - label: Distance Healing
    name: distance-healing
    file: "/content/en/data/distance-healing.yml"
    fields:
    - name: title
      widget: string
    - name: access
      widget: object
      fields:
      - {name: title, widget: string}
      - {name: subtitle, widget: string}
      - {name: image, widget: image}
      - name: team
        label: team members
        widget: list
        fields: 
        - name: name
          widget: string
        - name: bio
          widget: string
      - name: prices
        widget: list
        fields:
        - {name: text, widget: string}
        - {name: time, widget: string}
        - {name: price, widget: number}
      - {name: text_1, widget: markdown}
      - {name: text_2, widget: markdown}
    - name: join_team
      label: join team
      widget: object
      fields:
      - {name: title, widget: string}
      - {name: image, widget: image}
      - {name: text_1, widget: markdown}
      - {name: text_2, widget: markdown}
    - name: support
      widget: object
      fields:
      - {name: title, widget: string}
      - {name: image, widget: image}
      - {name: text_1, widget: markdown}
      - {name: text_2, widget: markdown}

  - label: Prices
    name: prices
    file: "/content/en/data/prices.yml"
    fields:
    - name: title
      widget: string
    - name: details
      widget: markdown
  - label: Prices table
    name: prices-table
    file: /content/en/data/prices-table.md
    fields:
    - name: body
      widget: markdown

  - label: Testimonials
    name: testimonials
    file: "/content/en/data/testimonials.yml"
    fields:
    - name: items
      label: testimonials
      widget: list
      fields:
      - {name: name, widget: string}
      - {name: image, widget: image}
      - {name: stars, widget: number}
      - {name: date, widget: date}
      - {name: response, widget: text}

  - name: therapies
    label: Therapies
    file: "/content/en/data/therapies.yml"
    fields:
    - name: title
      widget: string
    - name: col1
      widget: markdown
    - name: col2
      widget: markdown
    - name: content
      widget: markdown
    - name: gallery_text
      widget: markdown
    - name: details
      widget: markdown

- name: sections-en
  label: sections English
  editor:
    preview: true
  files:
  - name: "navigation"
    label: "navigation menu"
    file: "/content/en/data/navigation.yml"
    fields:
    - label: "Navigation items"
      name: "items"
      widget: "list"
      fields:
      - { label: "label", name: "label", widget: "string" }
      - { label: "link",  name: "link",  widget: "string", default: "#" }
      - { label: "order",  name: "order",  widget: "number", default: "9" }

- name: "text-en"
  label: "Text sections English"
  folder: "/content/en/data"
  create: true
  fields:
  - {label: "page", name: "page", widget: "string"}
  - {label: "section", name: "section", widget: "string"}
  - {label: "Body", name: "body", widget: "markdown"}

##########################################
- name: pages-fr
  label: Pages France
  editor:
    preview: true
  files:
  - label: Homepage
    name: homepage
    file: "/content/fr/data/home.yml"
    fields:
    - name: title
      widget: string
    - name: subtitle
      widget: string
    - name: text
      widget: string
    - name: about_section
      label: About section
      widget: object
      fields: 
      - {name: intro, widget: text}
      - {name: decor_center, widget: image}
      - {name: decor_left, widget: image}
      - {name: decor_right, widget: image}
      - {name: image_1, widget: image}
      - {name: image_2, widget: image}
      - name: about_box
        widget: object
        fields: 
        - {name: image, widget: image}
        - {name: name, widget: string}
        - {name: title, widget: string}
        - {name: text, widget: markdown}

      - name: therapies
        widget: object
        allow_add: false
        fields: 
        - {name: cta_label, widget: string}
        - {name: cta_link, widget: string}        
        - {name: title, widget: string}
        - name: items
          allow_add: false
          widget: list
          fields: 
          - {name: title, widget: string}
          - {name: image, widget: image}

    - name: gallery
      widget: list
  #    field:
  #    - {name: slide, widget: list, field: {name: image, widget: image}}
  #      
    - name: decor_gallery
      widget: image
    - name: distance
      widget: object
      fields: 
      - {name: decor_center, widget: image}
      - {name: title, widget: string}
      - {name: text, widget: markdown}
      - name: three_t
        allow_add: false
        widget: list
        fields: 
        - {name: label, widget: string}
        - {name: image, widget: image}
    - name: contact
      widget: object
      fields:
      - {name: image, widget: image}
      - {name: text, widget: list}
 
  - label: Distance Healing
    name: distance-healing
    file: "/content/fr/data/distance-healing.yml"
    fields:
    - name: title
      widget: string
    - name: access
      widget: object
      fields:
      - {name: title, widget: string}
      - {name: subtitle, widget: string}
      - {name: image, widget: image}
      - name: team
        label: team members
        widget: list
        fields: 
        - name: name
          widget: string
        - name: bio
          widget: string
      - name: prices
        widget: list
        fields:
        - {name: text, widget: string}
        - {name: time, widget: string}
        - {name: price, widget: number}
      - {name: text_1, widget: markdown}
      - {name: text_2, widget: markdown}
    - name: join_team
      label: join team
      widget: object
      fields:
      - {name: title, widget: string}
      - {name: image, widget: image}
      - {name: text_1, widget: markdown}
      - {name: text_2, widget: markdown}
    - name: support
      widget: object
      fields:
      - {name: title, widget: string}
      - {name: image, widget: image}
      - {name: text_1, widget: markdown}
      - {name: text_2, widget: markdown}

  - label: Prices
    name: prices
    file: "/content/fr/data/prices.yml"
    fields:
    - name: title
      widget: string
    - name: details
      widget: markdown
  - label: Prices table
    name: prices-table
    file: /content/fr/data/prices-table.md
    fields:
    - name: body
      widget: markdown

  - label: Testimonials
    name: testimonials
    file: "/content/fr/data/testimonials.yml"
    fields:
    - name: items
      label: testimonials
      widget: list
      fields:
      - {name: name, widget: string}
      - {name: image, widget: image}
      - {name: stars, widget: number}
      - {name: date, widget: date}
      - {name: response, widget: text}

  - name: therapies
    label: Therapies
    file: "/content/fr/data/therapies.yml"
    fields:
    - name: title
      widget: string
    - name: col1
      widget: markdown
    - name: col2
      widget: markdown
    - name: content
      widget: markdown
    - name: gallery_text
      widget: markdown
    - name: details
      widget: markdown

- name: sections-fr
  label: sections France
  editor:
    preview: true
  files:
  - name: "navigation"
    label: "navigation menu"
    file: "/content/fr/data/navigation.yml"
    fields:
    - label: "Navigation items"
      name: "items"
      widget: "list"
      fields:
      - { label: "label", name: "label", widget: "string" }
      - { label: "link",  name: "link",  widget: "string", default: "#" }
      - { label: "order",  name: "order",  widget: "number", default: "9" }

- name: "text-fr"
  label: "Text sections France"
  folder: "/content/fr/data"
  create: true
  fields:
  - {label: "page", name: "page", widget: "string"}
  - {label: "section", name: "section", widget: "string"}
  - {label: "Body", name: "body", widget: "markdown"}
####################################

- name: pages-de
  label: Pages Germany
  editor:
    preview: true
  files:
  - label: Homepage
    name: homepage
    file: "/content/de/data/home.yml"
    fields:
    - name: title
      widget: string
    - name: subtitle
      widget: string
    - name: text
      widget: string
    - name: about_section
      label: About section
      widget: object
      fields: 
      - {name: intro, widget: text}
      - {name: decor_center, widget: image}
      - {name: decor_left, widget: image}
      - {name: decor_right, widget: image}
      - {name: image_1, widget: image}
      - {name: image_2, widget: image}
      - name: about_box
        widget: object
        fields: 
        - {name: image, widget: image}
        - {name: name, widget: string}
        - {name: title, widget: string}
        - {name: text, widget: markdown}

      - name: therapies
        widget: object
        allow_add: false
        fields: 
        - {name: cta_label, widget: string}
        - {name: cta_link, widget: string}        
        - {name: title, widget: string}
        - name: items
          allow_add: false
          widget: list
          fields: 
          - {name: title, widget: string}
          - {name: image, widget: image}

    - name: gallery
      widget: list
  #    field:
  #    - {name: slide, widget: list, field: {name: image, widget: image}}
  #      
    - name: decor_gallery
      widget: image
    - name: distance
      widget: object
      fields: 
      - {name: decor_center, widget: image}
      - {name: title, widget: string}
      - {name: text, widget: markdown}
      - name: three_t
        allow_add: false
        widget: list
        fields: 
        - {name: label, widget: string}
        - {name: image, widget: image}
    - name: contact
      widget: object
      fields:
      - {name: image, widget: image}
      - {name: text, widget: list}
 
  - label: Distance Healing
    name: distance-healing
    file: "/content/de/data/distance-healing.yml"
    fields:
    - name: title
      widget: string
    - name: access
      widget: object
      fields:
      - {name: title, widget: string}
      - {name: subtitle, widget: string}
      - {name: image, widget: image}
      - name: team
        label: team members
        widget: list
        fields: 
        - name: name
          widget: string
        - name: bio
          widget: string
      - name: prices
        widget: list
        fields:
        - {name: text, widget: string}
        - {name: time, widget: string}
        - {name: price, widget: number}
      - {name: text_1, widget: markdown}
      - {name: text_2, widget: markdown}
    - name: join_team
      label: join team
      widget: object
      fields:
      - {name: title, widget: string}
      - {name: image, widget: image}
      - {name: text_1, widget: markdown}
      - {name: text_2, widget: markdown}
    - name: support
      widget: object
      fields:
      - {name: title, widget: string}
      - {name: image, widget: image}
      - {name: text_1, widget: markdown}
      - {name: text_2, widget: markdown}

  - label: Prices
    name: prices
    file: "/content/de/data/prices.yml"
    fields:
    - name: title
      widget: string
    - name: details
      widget: markdown
  - label: Prices table
    name: prices-table
    file: /content/de/data/prices-table.md
    fields:
    - name: body
      widget: markdown

  - label: Testimonials
    name: testimonials
    file: "/content/de/data/testimonials.yml"
    fields:
    - name: items
      label: testimonials
      widget: list
      fields:
      - {name: name, widget: string}
      - {name: image, widget: image}
      - {name: stars, widget: number}
      - {name: date, widget: date}
      - {name: response, widget: text}

  - name: therapies
    label: Therapies
    file: "/content/de/data/therapies.yml"
    fields:
    - name: title
      widget: string
    - name: col1
      widget: markdown
    - name: col2
      widget: markdown
    - name: content
      widget: markdown
    - name: gallery_text
      widget: markdown
    - name: details
      widget: markdown

- name: sections-de
  label: sections Germany
  editor:
    preview: true
  files:
  - name: "navigation"
    label: "navigation menu"
    file: "/content/de/data/navigation.yml"
    fields:
    - label: "Navigation items"
      name: "items"
      widget: "list"
      fields:
      - { label: "label", name: "label", widget: "string" }
      - { label: "link",  name: "link",  widget: "string", default: "#" }
      - { label: "order",  name: "order",  widget: "number", default: "9" }

- name: "text-de"
  label: "Text sections Germany"
  folder: "/content/de/data"
  create: true
  fields:
  - {label: "page", name: "page", widget: "string"}
  - {label: "section", name: "section", widget: "string"}
  - {label: "Body", name: "body", widget: "markdown"}
